version: 2
jobs:
  deploy_cron:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: /ws
    steps:
      - checkout
      - run:
          name: "Set Project"
          command: gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: "...appengine"
          command: cd appengine
      - run:
          name: "PIP install"
          command: pip install -t lib -r requirements.txt
      - run:
          name: "app create?"
          command: gcloud app create
      - run:
          name: "Deploy the application to App Engine"
          command: gcloud app deploy app.yaml \cron.yaml
  deploy_functions:
    docker:
      - image: devillex/docker-firebase
    working_directory: /ws
    steps:
      - run: firebase functions:config:set sparkpost.key="$SPARKPOST_API_KEY"
      - run: firebase deploy --only functions --project $FIREBASE_PROJECT_ID
workflows:
  version: 2
  deploy_and_deploy:
    jobs:
      - deploy_cron
      - deploy_functions
