version: 2
jobs:
  deploy_cron:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: /ws
    steps:
      - checkout
      - run:
          name: Decrypt Keys
          command: openssl enc -d -a -aes-256-cbc -k $GCLOUD_ENCRYPTION_KEY -in appengine/client-secret.json.enc -out ${HOME}/gcloud-service-key.json
      - run:
          name: Project settings
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: Install appengine/Python dependecies
          command: |
            cd appengine
            pip install -t lib -r requirements.txt
            gcloud app deploy app.yaml \cron.yaml
  deploy_functions:
    docker:
      - image: datagovsg/python-node
    working_directory: /ws
    steps:
      - checkout
      - run: 
          name: Firebase Config and Deploy
          command: |
            npm install firebase-admin@latest
            npm install firebase-functions@latest
            firebase use $FIREBASE_PROJECT_ID
            firebase functions:config:set sparkpost.key="$SPARKPOST_API_KEY" --token "$FIREBASE_TOKEN"
            firebase deploy --only functions --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  deploy_and_deploy:
    jobs:
      - deploy_cron:
          context: autotimeline
      - deploy_functions:
          context: autotimeline
