version: 2
jobs:
  deploy_cron:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: /ws
    steps:
      - checkout
      - run:
          name: "Set Project"
          command: gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: Install appengine/Python dependecies
          command: |
            cd appengine
            pip install -t lib -r requirements.txt
            gcloud app create
            gcloud app deploy app.yaml \cron.yaml
  deploy_functions:
    docker:
      - image: devillex/docker-firebase
    working_directory: /ws
    steps:
      - run: firebase functions:config:set sparkpost.key="$SPARKPOST_API_KEY" --project $FIREBASE_PROJECT_ID
      - run: firebase deploy --only functions --project $FIREBASE_PROJECT_ID
workflows:
  version: 2
  deploy_and_deploy:
    jobs:
      - deploy_cron:
          context: autotimeline
